In [6]:
import numpy as np
import pandas as pd
from sklearn.decomposition import TruncatedSVD

users = ["u1", "u2", "u3", "u4", "u5"]
items = ["Politics", "Tech", "Sports", "Finance", "Health", "Travel", "Food"]

R = np.array([
    [1, 1, 0, 0, 0, 0, 1],
    [1, 1, 0, 1, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0],
    [0, 0, 1, 0, 1, 1, 0],
    [1, 0, 0, 1, 0, 0, 1],
])

df = pd.DataFrame(R, index=users, columns=items)
df

    Politics  Tech  Sports  Finance  Health  Travel  Food
u1         1     1       0        0       0       0     1
u2         1     1       0        1       0       0     0
u3         0     0       1        1       1       0     0
u4         0     0       1        0       1       1     0
u5         1     0       0        1       0       0     1

In [7]:
k = 2

svd = TruncatedSVD(n_components=k, random_state=42)
P = svd.fit_transform(R)
Q = svd.components_.T

S_hat = P @ Q.T
score_df = pd.DataFrame(S_hat, index=users, columns=items)
score_df

    Politics      Tech    Sports   Finance    Health    Travel      Food
u1  0.990623  0.668372 -0.159051  0.619664 -0.159051 -0.134213  0.668372
u2  0.978204  0.650227  0.081600  0.749972  0.081600 -0.012419  0.650227
u3  0.163200  0.069181  0.974055  0.680791  0.974055  0.481302  0.069181
u4 -0.159051 -0.146632  0.986474  0.456464  0.986474  0.505172 -0.146632
u5  0.978204  0.650227  0.081600  0.749972  0.081600 -0.012419  0.650227

In [9]:
def recommend_for_user(user_id, R, scores, users, items, top_k=3):
    u_idx = users.index(user_id)
    seen = R[u_idx] > 0

    user_scores = scores[u_idx].copy()
    user_scores[seen] = -np.inf

    top_indices = np.argsort(user_scores)[::-1][:top_k]
    return [(items[i], float(user_scores[i])) for i in top_indices]

recommend_for_user("u1", R, S_hat, users, items, top_k=4)

[('Finance', 0.6196638730075948),
 ('Travel', -0.13421342193127683),
 ('Health', -0.15905113688685024),
 ('Sports', -0.15905113688685024)]